### ISSUE TITLE
Sliders drift in Settings menu

### ISSUE THREAD

**Issue by Kleadron** [TheOverfloater/pathos-public#1]
After changing and applying a setting in the settings menu that is represented as a slider, it has a chance to drift to a lower value when you open the menu again. Video attached shows the behavior.

https://github.com/TheOverfloater/pathos-public/assets/39423518/565a6329-898a-47cb-a9e6-0515fb6e2bcf

**Comment by TheOverfloater** [comment]
I've resolved this issue in the commit 0ce5b01 by using proper floating-point variables to calculate the positions of the UI slider buttons. I tested this myself numerous times, and the issue seems to be fixed, hence closing.
