### ISSUE TITLE
-game doesn't load all files from mod folder

### ISSUE THREAD

**Issue by AnthonyPython** [TheOverfloater/pathos-public#13]
it doesn't load the -game's dir for quite a few things it seems when the pathos folder doesn't exist including fonts and various others like gameinfo.cfg
I do not know the extent how many but I noticed at first it was only loading the default pathos gameinfo.cfg

(note this was a direct copy of pathos folder for testing so there was no missing files while the pathos folder still exist)

**Comment by AnthonyPython** [comment]
how ever it did load the titles.txt from the folder so I know that works

**Comment by TheOverfloater** [comment]
Thank you for notifying me. This issue has been fixed in commit 2f660c6.
