### ISSUE TITLE
does this engine use 100% original code?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#15]
i want to make my own standalone games and like upload on steam and stuff, and i like half-life styled engines because of their level editor and stuff, so does this use 100% original code which would mean possible to do that? not related to this is im wondering what is BSS that shaders use, i wanna make my own custom shaders and im familiar with opengl that it seems to be based on but i have never heard of BSS, hoping for an answer and thanks for making this

**Comment by valina354** [comment]
i looked in readme.txt and it says "Valve Software for the code referenced from the Half-Life SDK while developing this project." however half-life sdk doesnt allow anything to be used out of the half-life engine and is one of the main reasons why another project called xash3d isnt legal mostly

**Comment by TheOverfloater** [comment]
Referenced != copied - I looked at some SDK code to see how they were doing some things, but I did not copy any code from the Half-Life SDK, basically having used Clean room design to recreate the functionality of Half-Life features I depended on with my own game. This means it's 100% original code that behaves mostly the same as some Half-Life code did, but it does not in any way infringe upon the SDK license or copyright.

BSS is explained under the docs folder, it's a proprietary scripting language used to define a single ubershader that is then split into multiple unique shaders along the $if branches. This means that a specific rendering module uses a single BSS ubershader script to compile all it's unique shaders it needs.

**Comment by valina354** [comment]
> Referenced != copied - I looked at some SDK code to see how they were doing some things, but I did not copy any code from the Half-Life SDK, basically having used Clean room design to recreate the functionality of Half-Life features I depended on with my own game. This means it's 100% original code that behaves mostly the same as some Half-Life code did, but it does not in any way infringe upon the SDK license or copyright.
> 
> BSS is explained under the docs folder, it's a proprietary scripting language used to define a single ubershader that is then split into multiple unique shaders along the $if branches. This means that a specific rendering module uses a single BSS ubershader script to compile all it's unique shaders it needs.

ok i understand, guess i will close this as complete

**Comment by valina354** [comment]
forgot to ask this but im wondering what about compilers? they seem to be based on vhlt but im guessing the compilers arent written from scratch, wouldnt that cause an issue? or probably not as long as i dont put the compilers in the game

**Comment by valina354** [comment]
i also see that some studio stuff (well this header that is in the released code) does use valve stuff, are these temporary till studiomdl is rewritten or something? (at least thats what i saw in readme something related to studiomdl being from sdk)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/58c2cc04-6973-43e1-ad31-3a827ca74289)

**Comment by TheOverfloater** [comment]
The file in question is still 100% custom code, I just kept the header, as the studiomdl format is not my invention. I kept studiomdl, as it is needed for VHE and Jack. There is no patent on the model format, so it is free to use by anyone. There are no plans to strip it out.

**Comment by TheOverfloater** [comment]
> forgot to ask this but im wondering what about compilers? they seem to be based on vhlt but im guessing the compilers arent written from scratch, wouldnt that cause an issue? or probably not as long as i dont put the compilers in the game

The compilers are VHLT based yes, but as far as I am aware, there's no limiting factor that prevents their use outside of Half-Life, as they sre not part of the HLSDK nor do they contain any original HLSDK code.

**Comment by valina354** [comment]
> The file in question is still 100% custom code, I just kept the header, as the studiomdl format is not my invention. I kept studiomdl, as it is needed for VHE and Jack. There is no patent on the model format, so it is free to use by anyone. There are no plans to strip it out.

im just a tiny bit worried about this, like i dont understand if it means original code from hl sdk was taken or just that studiomdl format isnt your invention so that was placed there @TheOverfloater 
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/6d1547e7-6cd0-460d-bfd5-dde992f4f163)

**Comment by TheOverfloater** [comment]
@valina354 It means the studiomdl format is not my invention so I don't have any ownership of it. Otherwise no code was taken from the HLSDK. I will clarify this in the file.

**Comment by valina354** [comment]
@TheOverfloater 
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/caba51bc-ddd4-40c0-958c-a936d6a283f7)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/d0a874a8-ec9d-41e9-851b-0403194818cb)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/3ab4790b-8c24-4bd1-a65b-88b31fbfd7b0)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/8cfc62f1-7c0c-4838-a41f-44996f6fdc2e)

qrad.cpp,qcsg.cpp,qbsp.cpp,vis.cpp mentions being based on valve original code due to being based on vhlt which probably doesnt matter much as long as they arent provided with final game but still its probably worrying

**Comment by TheOverfloater** [comment]
VHLT is separate from the Pathos repository, which was partly done to avoid any issues due to copyright or licenses, in case some Valve/Id Software code did remain. There's currently no plans to write my own level compilers for Pathos, so they just won't be distributed with the game itself.

**Comment by valina354** [comment]
> VHLT is separate from the Pathos repository, which was partly done to avoid any issues due to copyright or licenses, in case some Valve/Id Software code did remain. There's currently no plans to write my own level compilers for Pathos, so they just won't be distributed with the game itself.

i have been doing some investigation into the compilers and comparing functions and as of now i have found a bunch of valve/idtech code so the compilers should stay seperate from pathos repo as it is now
