### ISSUE TITLE
are dlights and spotlights broken?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#16]
i placed a env_dlight, turned on start on flag and compiled map however  there is no dynamic light, it seems to be affecting the specular highlights but not surfaces, i think dlight is supposed to be dynamic lights at least from the dynamic lighting video but it just doesnt work, env_spotlight too, unless im doing something wrong

**Comment by valina354** [comment]
i checked and first map that comes with game has a dlight at start yet after recompile they are gone, i use these compilers just recompiled them, unless they are broken https://github.com/TheOverfloater/pathos-vhlt

**Comment by TheOverfloater** [comment]
Please send your BSP/RMF files to me at doommusic666@hotmail.com

**Comment by valina354** [comment]
sent

**Comment by TheOverfloater** [comment]
You are using an extremely low radius value(15) on that env_dlight, so it doesn't affect the scene much. Specular highlights are visible because those have a somewhat stronger effect. Radius is in units.

**Comment by valina354** [comment]
i just now tried setting range to 500 and higher and still same thing its very strange

**Comment by TheOverfloater** [comment]
I checked further, and you specified the color information with a 4th component, the 100 at the end. It seems having 4 components for some reason broke the code that reads the values. I'll check and fix it so the 4th component is discarded and doesn't cause the code to fail, but for now just remove it, and your dynamic light should work.

**Comment by valina354** [comment]
> I checked further, and you specified the color information with a 4th component, the 100 at the end. It seems having 4 components for some reason broke the code that reads the values. I'll check and fix it so the 4th component is discarded and doesn't cause the code to fail, but for now just remove it, and your dynamic light should work.

i know that,  i tried that since i thought thats way to like change brightness of dyn light, but removing it doesnt fix it i have tried almost everything  its so confusing it fells like its got to do with compiler due to fact that recompiling a map from the provided maps breaks the dynlight  in the map but i dont know why

**Comment by valina354** [comment]
i dont know how but i changed a few lines in bsprenderer.bss shader and it somehow fixed it

**Comment by TheOverfloater** [comment]
I tried to reproduce the issue on my end but couldn't. What lines did you modify?
