### ISSUE TITLE
[Not an issue] Suggestion: Parallax Corrected Cubemaps

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#18]
Unlike one of my earlier suggestions this one is actually doable probably easy,  way it works is uses a bounding box (could be an entity say env_cubemap_box) the env_cubemap would have a slot for the env_cubemap_box to use (if not selected no parallax) some shader code and that would be it, it could probably take 1 day to a max of few to implement it i can probably help in doing it at least for shader code, but C++ code for env_cubemap_box is only thing i dont know how to do much, this paper could help https://seblagarde.wordpress.com/wp-content/uploads/2012/08/parallax_corrected_cubemap-siggraph2012.pdf

**Comment by TheOverfloater** [comment]
I am open to this suggestion, my original plan with cubemaps was indeed to add them as parallax corrected cubemaps, but I went out of budget in terms of time, and the math was a bit over my head. If you are open to editing the shader code, that's great, and I can give the math another go. However in this case I would drop support for the current version of cubemaps, and only support the parallax corrected type. I can't make any promises on how long this'd take to implement though.

**Comment by valina354** [comment]
> I am open to this suggestion, my original plan with cubemaps was indeed to add them as parallax corrected cubemaps, but I went out of budget in terms of time, and the math was a bit over my head. If you are open to editing the shader code, that's great, and I can give the math another go. However in this case I would drop support for the current version of cubemaps, and only support the parallax corrected type. I can't make any promises on how long this'd take to implement though.

sounds great, i can edit some of shader code as i know glsl quite a bit
