### ISSUE TITLE
[32-BIT ONLY] Lightmaps have misalignments or are incorrectly sized

### ISSUE THREAD

**Issue by Kleadron** [TheOverfloater/pathos-public#2]
**EDIT: It appears this issue only happens on the 32-bit build of the engine. So this might be a compilation or processor architecture issue instead.**
The following details are irrelevant but the screenshots still show the issue.

Due to inaccuracy in how lightmap textures are sized/aligned they can appear skewed or misaligned on some maps.

In GoldSrc, lightmap coordinates are generated based on how quake's software renderer uses surface cached textures which can be read about here:
https://www.bluesnews.com/abrash/chap68.shtml
https://www.bluesnews.com/abrash/chap69.shtml
basically; textures are stored and tiled in units of 16x16 tiles and lightmaps corespond to the shading applied to the corners of those tiles. A single 16x16 tile would have a 2x2 lightmap for example.
 
The following screenshots show comparisons from Pathos Engine and GoldSrc on de_dust2_cz from Counter-Strike: Condition Zero
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/fc59ab31-ef6b-4045-81ff-faf2307407a2)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/0645f9fe-85d7-44e5-9a6e-60426f0997ea)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/b3b83f2f-702a-4cc8-9672-a3d97076b57c)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/90b7f3f4-613b-454e-8be6-f20a436019d9)

**Comment by TheOverfloater** [comment]
I am still looking into this issue, and I will update this issue once I develop a solution.

**Comment by Kleadron** [comment]
It's been determined this is a compiler bug with floating point precision and is more easily fixed by using a newer visual studio toolset. Closing for now
