### ISSUE TITLE
[Not an issue] Suggestion: Flag to disable specular heighlights from dlights

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#20]
i have been trying to fake csm with env_dlights and its actually not that bad interms of performance too, however in certain scenarios specularity isnt always wanted while still keeping same material not requring a new one specially for outdoors, i can probably do this myself and send pull request although im not sure how
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/2590bb4e-85fd-4dcd-92e5-f7eabedffc22)

**Comment by TheOverfloater** [comment]
I can add a change for this, basically allowing you to set the specular factor for the individual dynamic light. That is preferable to introducing more branching via new determinators.

**Comment by valina354** [comment]
> I can add a change for this, basically allowing you to set the specular factor for the individual dynamic light. That is preferable to introducing more branching via new determinators.

that sounds great i guess
