### ISSUE TITLE
What exactly does rendering error invalid determinator values in shader mean?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#22]
I have been trying to add two blended textures (similar to displacement textures in source) to my fork of this, it works fine but when flashlight or any dlight is on the two blended textures disappear and when i turned on wireframe as long as flashlight is on theres no crash and instant when i turn it off there is which seems very strange as to why its not working
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/b3cfe5ec-143c-4eb2-87d1-eadf343543ec)

**Comment by TheOverfloater** [comment]
It means you've set up a state for the determinator values that is invalid when considering the non-usable, rejected shader states defined with $invalid_state statements in the BSS file. You need to verify that your determinators are properly reset prior to wireframe rendering. This feature is used to cut out shader states that would not be compatible with eachother and thus optimizes on the number of shader variations.

**Comment by valina354** [comment]
ok
