### ISSUE TITLE
[Not an issue] Suggestion: Detail props

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#24]
something similar like source would really make it easier to make forresty enviorments without as much performance loss https://developer.valvesoftware.com/wiki/Detail_props

**Comment by TheOverfloater** [comment]
This idea has been on the backburner for a while, and the idea would be to come up with a fake-random spawn generator for this so that the props don't change with a save/load. Once I make progress with such a concept, adding this shouldn't be a major hurdle.
