### ISSUE TITLE
question about map size limit

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#25]
i have been experimenting with map limit seeing if i can raise it higher, and while it mostly works as in compile works and stuff ingame its a bit broken  as if theres an issue with visibility but theres not, it seems related to frustum rendering as making bsp not init frustum fixes it altho that doesnt work cuz of course lights and way more things need frustum this is vid showing it i have looked through code and cant figure out why that could be happening so i thought only person to ask is owner itself, i did find that bsp format had int16 for some 'min' and 'max' stuff so i changed them to int32s and still didnt fix (cuz from what i know int16 only works up to 65536)

https://github.com/TheOverfloater/pathos-public/assets/80889633/acbb5c38-b54b-4911-a068-6ab0d79b3820

**Comment by valina354** [comment]
side note only brushes disappear vbm/mdls still show including dlights on them so it seems only a brush  issue


https://github.com/TheOverfloater/pathos-public/assets/80889633/92877b4b-0fcf-48c5-8fa6-2e7c12dfd277

**Comment by TheOverfloater** [comment]
I have been looking through the frustum, as well as other engine code, but there I haven't been able to identify anything that would explain this. However the int16 variables you mentioned in the bsp file's structs are my only guess so far. To be honest I never really considered it likely that anyone would have any reason to go outside the +/- 32768 range when making maps, so I kind of designated that the "limit" for Pathos's maps. For me personally not even my largest maps go outside +/- 8192 even. Another reason is that precision issues show up if you go too far outside 4096 with smaller texture scales on surfaces, making it extremely ill-advised to go that far from 0 0 0. Regardless, did you make sure to edit the VHLT for Pathos as well to use the new 32-bit integer types and recompiled the map with the new binaries?

**Comment by valina354** [comment]
> I have been looking through the frustum, as well as other engine code, but there I haven't been able to identify anything that would explain this. However the int16 variables you mentioned in the bsp file's structs are my only guess so far. To be honest I never really considered it likely that anyone would have any reason to go outside the +/- 32768 range when making maps, so I kind of designated that the "limit" for Pathos's maps. For me personally not even my largest maps go outside +/- 8192 even. Another reason is that precision issues show up if you go too far outside 4096 with smaller texture scales on surfaces, making it extremely ill-advised to go that far from 0 0 0. Regardless, did you make sure to edit the VHLT for Pathos as well to use the new 32-bit integer types and recompiled the map with the new binaries?

i have for vhlt tho i havent changed int16 in dbspv1node_t cuz i cant figure out where the similar int16 is for the vhlt, im pretty much trying to make engine be more openworld  pretty much since im making my own engine based on pathos, i will see about int16 at dbspv1node_t however
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/0f1fb133-e4d0-4149-b43f-53837838abe1)

**Comment by valina354** [comment]
yup it wasnt the dbspv1node_t being int16 as i just figured out where it was located in csg.h

**Comment by valina354** [comment]
commenting out r_setfrustum here fixes issue  so its 90% frustum issue, thing is i checked every param inputed into frustum and it seems correct 
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/3970cd1d-21c7-4bdb-95f5-2568a2882164)

**Comment by TheOverfloater** [comment]
I am going to look into this deeper, but at the moment I am struggling with ill health so it'll take a bit longer. In the meantime please send me your latest BSP file with the increased integer types for the mins/maxs to doommusic666@hotmail.com, so I can check on it.

**Comment by valina354** [comment]
> I am going to look into this deeper, but at the moment I am struggling with ill health so it'll take a bit longer. In the meantime please send me your latest BSP file with the increased integer types for the mins/maxs to [doommusic666@hotmail.com](mailto:doommusic666@hotmail.com), so I can check on it.

was gonna send but decided to recompile map to be sure and now it doesnt work and it happens with every map very strange i have never had this before 
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/753746ce-b88f-4ade-b5fe-751ffd92f79d)

**Comment by valina354** [comment]
oh wait whoops for some reason the compilers are gone from the compile folder strange

**Comment by valina354** [comment]
well i somehow managed to break even bsp textures loading in my branch past the map limit so at this point its probably not even worth it and i agree on map limit i guess its just not worth it
