### ISSUE TITLE
[Not an issue] Suggestion: Make cubemaps get darker if the lighting is darker

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#27]
i think this would enhance the graphical quality of cubemaps a lot and would prevent things like this where cubemap is very bright even in shadow
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/4dd3fc0c-fa6b-464b-b0bc-a7b5d648f007)

**Comment by TheOverfloater** [comment]
I would need to check up on how other video games do this, cause off the top of my head I am not sure of a way to do this that properly accounts for darkness.

**Comment by valina354** [comment]
> I would need to check up on how other video games do this, cause off the top of my head I am not sure of a way to do this that properly accounts for darkness.

![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/18f607e5-356d-4474-af32-69e96eed4e7e)
source engine does do it somehow according to vdc but im not exactly sure how, but it seems to be related to lightmapping, so in pathos it could probably be done based on lightmap and then maybe somehow acount for dlights?? im not sure
