### ISSUE TITLE
Font textures are incorrectly blended or colored

### ISSUE THREAD

**Issue by Kleadron** [TheOverfloater/pathos-public#3]
The code that converts font glyphs to texture data in r_text.cpp uses a grayscale value for both the RGB channels and the Alpha channel.
https://github.com/TheOverfloater/pathos-public/blob/f676bc15c2bb6a6ed55330824fb17e35d7814464/pathos/sources/codesrc/engine/renderer/r_text.cpp#L350-L391
They are blended using regular alpha blending which means the edges appear darkened when drawn to the screen.
Using a premultipled blend function, or making the RGB channels of the texture always white (as was done in this example) fixes the issue.

![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/4493343b-3fde-4f73-bf97-488fe5878821)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/7caf6d7d-4ada-4c26-bc4f-648b5c0940f4)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/c3afa569-2f75-4394-965c-f4f87d88e267)
![image](https://github.com/TheOverfloater/pathos-public/assets/39423518/410c49ce-2825-409d-9738-d5019e264edb)

A notable side effect is the text on the main menu being a solid color and blending into the background a lot more easily.

**Comment by TheOverfloater** [comment]
Thank you for letting me know. This issue has been fixed in the latest commit 0ce5b01 fixes this issue and the color of the font pixels is now properly set.
