### ISSUE TITLE
[Not an issue] Is work being done on the studiomdl rewrite?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#30]
i wanna start improving the mdl format for my engine based on this but i pretty much cant untill the studiomdl rewrite so it can be opensourced since i want to raise like limits and stuff and features

**Comment by TheOverfloater** [comment]
The studiomdl rewrite is currently on hold due to the fact that I have higher priority issues at the moment, like extending the test levels, and also I am currently in the hospital due to liver disease, so everything is on hold at the moment.

**Comment by TheOverfloater** [comment]
@valina354 Just wanted to let you know, if it's still relevant to you, that I began rework on the studiomdl rewrite for Pathos. I can't promise when I will be done, but it's in the works.

**Comment by valina354** [comment]
> [@valina354](https://github.com/valina354) Just wanted to let you know, if it's still relevant to you, that I began rework on the studiomdl rewrite for Pathos. I can't promise when I will be done, but it's in the works.

yeah its not relevant to me anymore as i have stopped using pathos and moved to making my own engine inspired a lot by pathos and source but with better graphics, hopefully it will help others though the studiomdl rewrite

**Comment by valina354** [comment]
> [@valina354](https://github.com/valina354) Just wanted to let you know, if it's still relevant to you, that I began rework on the studiomdl rewrite for Pathos. I can't promise when I will be done, but it's in the works.

just to let you know, i included you in credits of my engine, as i did use and reference some code from pathos https://github.com/Soft-Sprint-Studios/Tectonic-Engine/blob/main/credits.md let me know if related to pathos part of credits its alright for you or i should change anything related to it

**Comment by TheOverfloater** [comment]
> > [@valina354](https://github.com/valina354) Just wanted to let you know, if it's still relevant to you, that I began rework on the studiomdl rewrite for Pathos. I can't promise when I will be done, but it's in the works.
> 
> just to let you know, i included you in credits of my engine, as i did use and reference some code from pathos https://github.com/Soft-Sprint-Studios/Tectonic-Engine/blob/main/credits.md let me know if related to pathos part of credits its alright for you or i should change anything related to it

Thank you for crediting me, no need to change anything.
