### ISSUE TITLE
[Not an issue] Suggestion: Physics props

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#31]
i think this feature would be one of those that would pretty much benefit everyone  which are physics props, similar to source as they would make it very easy to  pickup props and stuff

**Comment by TheOverfloater** [comment]
Adding physics right now is a bit out of scope, maybe once I am done adding all the missing portions of the test levels, and the missing documentation, and the studiomdl replacement is done. I never have touched physics engines myself, but I am interested in taking a look so this is definitely a possibility.

**Comment by valina354** [comment]
i have been wondering if instead of a full on physics system like bullet or physx instead an easier way would be to make a simpler physics engine for engine  which would make it easier to implement some physics, but it would probably not be worth the effort and would result in bad physics

**Comment by TheOverfloater** [comment]
If I did physics, I would prefer to implement them the proper way.
