### ISSUE TITLE
[Not an issue] general place to bind textures  in r_bsp.cpp?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#37]
i added parallax occlusion mapping to engine but i got issue which is that for some reason when dlights are on the texture binding itself breaks or something and bleeds into other ones i added this
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/9a31da5a-fb09-4f98-aed6-05bc5ac3efff)
and this
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/01f519c3-74af-49b2-b067-9de41b86385d)

below 
if(pmaterial->ptextures[MT_TX_LUMINANCE])
{

functions, in area with no dlight it looks fine like this
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/7bba2b78-07ea-4d0f-a24a-ee884fbbed08)

but in area with dlight it breaks
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/1f8d16b3-7124-4857-be08-7317eb2914b9)

without height texture being defined this doesnt happen, so i think im binding in wrong places

**Comment by valina354** [comment]
@TheOverfloater

**Comment by valina354** [comment]
i notice when entering dlight area this stops triggering inside of BindTextures everything else too most likely causing the issue
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/b22edb2d-cf9f-49b1-9341-94b65f985fba)

**Comment by valina354** [comment]
when outside of dlight only bindtextures runs, and when inside dlight only drawfirst runs, i dont get what im doing wrong, im doing exact same as mt_tx_luminance

**Comment by valina354** [comment]
it also occurs for mt_tx_ao i added

**Comment by valina354** [comment]
this is my entire r_bsp.cpp to btw https://pastebin.com/gmPaQQtE

**Comment by TheOverfloater** [comment]
I'm afraid I can't really help here unless I were there to debug the code myself. Basically you need to use the debugger yourself to see why it doesn't trigger to begin with, it means you could be trying to use the wrong material, or that particular texture unit itself is being set to null for some reason. VS2022 allows you to set a breakpoint that triggers when a value in memory is changed, it is called a Data Breakpoint.

**Comment by valina354** [comment]
i notice same thing occurs with mt_tx_luminance but in luminance it doesnt break it which is strange and it also cant be shader related because same thing occurs with ao which is well very simple just multiply  by binded ao map so very strange

**Comment by valina354** [comment]
i figured out i need to also blind in drawlights however it seems to cause another issue, for some reason it seems only normal and specular gets displaced, not maintexture while without dlight it renders fine very strange
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/140c44d1-ecd6-4b15-96e0-c83f16b4d9ee)

**Comment by valina354** [comment]
it seems that for some reason when doing dlight it doesnt bind maintexture but even manually binding it doesnt fix

**Comment by valina354** [comment]
i now tested with default luminance and even that is broken, doesnt work correctly in dlight area, i wonder if i somehow broke some code in r_bsp.cpp that is causing it its like hardest thing to debug
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/63dfc055-bab0-4e34-a4a4-9ac2ec7748bd)

**Comment by valina354** [comment]
i love this engine a lot but the way rendering system is done is just so confusing in my opinion, like theres drawfirst,drawfinal,draw lights, and probably other places where you bind textueres, binding textures is literall more complex then the shaders themself, like in most other engines you just bind the textures in 1 function and thats it

**Comment by valina354** [comment]
i guess my only way is to try and copy paste how MT_TX_NORMALMAP binds textures and hope it works but i dont even know if that will work

**Comment by valina354** [comment]
i tried repeating similar to MT_TX_NORMALMAP but unless i did it wrong it stll happens, it basiclly seems to  pretty much paste the same ao map on another unrelated textures and i cant tell why

**Comment by valina354** [comment]
btw if you want to check it out yourself the issue engine is here https://github.com/Soft-Sprint-Studios/Matrix-Engine

**Comment by valina354** [comment]
for vbm i literally just did this in drawmesh and it worked for both dlights and normal lights while bsp is lot of stuff
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/990f6b27-492c-4c7b-88bb-1a2f9c09557f)

**Comment by valina354** [comment]
ok, so the only thing i can think of is that determinators are past 4096, basiclly i raised the limit to 8192 in C++, im not sure if that could be like causing it? has it been tested if more then 4096 determinators can work at same time? because with the ao and parallax i reached 7000 determinators @TheOverfloater

**Comment by valina354** [comment]
i also didnt add r_checkshaderuniform to all of them but i dont think thats issue

**Comment by valina354** [comment]
> ok, so the only thing i can think of is that determinators are past 4096, basiclly i raised the limit to 8192 in C++, im not sure if that could be like causing it? has it been tested if more then 4096 determinators can work at same time? because with the ao and parallax i reached 7000 determinators @TheOverfloater

i removed screen space normals termporarily to get it down below 4096 but that didnt fix it so its not issue that

**Comment by valina354** [comment]
omg ok, so i added ao and parallax here and it seemed to fix it! ao fully works fine without bleeding into others, however 
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/fa09fcae-c06a-40fd-8fac-c863457d71be) 

however parallax breaks with a dlight,  this no dlight
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/e370b9e0-d75a-46fa-b172-162efdb079eb)
and this with dlight
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/fe2f5cef-ae70-4ea8-bb21-64a1be23177c)

i think dlights how they render somehow coincide with parallax or somehow break it  i need to test more however

**Comment by valina354** [comment]
ye its caused by the weird strange bug from before with for some reason on dlight only showing parallax on normalmap i dont understand how i would fix it

**Comment by TheOverfloater** [comment]
Without seeing the shader code, and the BSP Renderer changes I cannot really tell what is wrong, but I assume you would need to account for parallax mapping both when rendering the first pass(lightmaps only), then account for it with each individual dynamic light, and finally account for it again in the third pass(rendering the texture, then rendering specular highlights, cubemaps). Make sure you have these stages also account for the parallax mapping, otherwise yes, it will break.

**Comment by valina354** [comment]
i seriously dont know what to do, i added to drawfinal as its final place to bind shaders that wasnt there and yet it still didnt fix it, this is my r_bsp.cpp https://github.com/Soft-Sprint-Studios/Matrix-Engine/blob/main/matrix/sources/codesrc/engine/renderer/r_bsp.cpp and this is the shader https://github.com/Soft-Sprint-Studios/Matrix-Engine/blob/main/matrix/scripts/shaders/bsprenderer.bss if you like have any free time to check it out because tbh i dont know myself i have been checking for last few days and cant figure it out

**Comment by valina354** [comment]
the only thing i can think of is issue in drawfinal  but i cant figure out how to fix it if that is the issue

**Comment by valina354** [comment]
i notice without a diffuse texture so only normal,specular,ao and height it seems to look normal, could that point to something? like related to diffuse @TheOverfloater  
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/b30fd0fa-6792-43fa-893a-c92decc1059e)

**Comment by valina354** [comment]
i checked with nsight and the parallax goes away for diffuse during where it binds the diffuse texture as it shows this with nsight, you can see parallax working fine right before diffuse  gets binded (also why is it getting binded sepeartly?)
https://github.com/TheOverfloater/pathos-public/assets/80889633/159782c7-1143-4869-88e0-db8ccda3b060

**Comment by valina354** [comment]
tested with no dlight, directly binds diffuse and all textures at same time, causing no issue, so that might be issue, unless im wrong

**Comment by valina354** [comment]
got screenshot of it dirrectly light on the surface and parallax there rightbefore binding diffuse
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/f04ced03-6965-46c0-9581-849fc473e4d2)

**Comment by valina354** [comment]
it seems it doesnt actually bind texture but just  redo gldrawelements for some reason and then parallax breaks there, which seems to contain maintexture and height texture
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/609762b7-00b9-4542-9116-2640b2587e8e)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/8b185453-7993-42ad-980d-40942540bb21)

**Comment by valina354** [comment]
it seems to defintly be issue maintexture, but issue is i cant hook up vs 2022 debugger and nsight at same time to go through code and see whats causing it

**Comment by valina354** [comment]
i have a felling its related to drawfinal but im not sure as it seems correct
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/b5aa3d5f-eccc-45e7-9c63-f5e9bd93c8df)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/408289d6-0f79-421e-aee5-4b34f994ef37)

**Comment by valina354** [comment]
i did even more tries at fixing yet still unfixed

**Comment by valina354** [comment]
i think i will try to remove everything i did about mt_tx_height in r_bsp.cpp and try again from fresh start  copying how specular,normal do it to bind and set for dlights and stuff

**Comment by TheOverfloater** [comment]
I haven't yet had time to check on your code, I am still busy with IRL things and I am also working on the next major Pathos update. Once I am done with these things, I can examine your code and try to see what might be wrong. However, based on my own experience, it's sometimes good to start from scratch. It's part of the learning process.

**Comment by valina354** [comment]
i tried starting from fresh and  copy and pasted how normal does it yet same issue so hopefully you can check it out soon

**Comment by valina354** [comment]
tbh its very annoying how like the C++ part is way more complex then shader itself im spending more time trying to fix C++ part then i did with shader which at start i thought would be most complex thing

**Comment by valina354** [comment]
i do notice normal maps even break parallax somehow, heres with normal map
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/d1be4958-ac6d-4a59-8315-fda9d4c3090f)
and no normal map (well full blue normal map) so im not sure why thats happening
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/39980d7c-f796-42f5-82ea-ed42d6bc1267)
i think its an issue with how normal maps render in engine, like what i mean is normal map isnt in correct place with parallax depth causing it to look weird

**Comment by valina354** [comment]
nvm figured out it was shader issue so i fixed it, only issue now seems to be with dlight, this is what happens with dlight now, for some reason diffuse texture goes bye bye, and performance goes bye bye too so hopefully you can try to investigate the issue cuz im so close to getting it working, i think it seems like it renders surface 2 times with parallax or like 3 times (draw first,draw lights,draw final) causing too much performance loss)
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/46fe3adf-cf37-4764-9295-aad5e0436580)

**Comment by valina354** [comment]
i fell like going crazy tbh cuz  i have checked everything i can think of, and its very important i get it working asap since im gonna make test maps and make my first game based on this and just in general have working parallax cuz it looks cool

**Comment by valina354** [comment]
im trying to debug more myself, like testing if d_parallax isnt true when in drawfinal cycle but for some reason it says unable to read memory so i kinda cant when checking 'this'
![image](https://github.com/user-attachments/assets/330ccce9-77ea-44fb-aac9-5bf34619800f)
![image](https://github.com/user-attachments/assets/0f9d8049-6724-4b3b-8ae5-c242bb45c600)

**Comment by valina354** [comment]
i tried to retry doing like how specular does it and it seems to work better, it fixes issue of diffuse texture going bye bye, but still parallax doesnt show and it creates these weird darker areas, but its similar to how specular does it so debugging should be easier when you check it out
![image](https://github.com/user-attachments/assets/86dc3c93-0009-497b-85cd-30f4398ee005)

**Comment by valina354** [comment]
i decided to change it more so its just how mt_tx_luminance binds which means it doesnt do anything with dlights now, but i have still been trying to debug it almost nonstop and still havent figured out and i dont know what to do anymnore, just this tiny bug is preventing me from being able to continue making my game because i want to use parallax mapping i added work with dlights as i want to use it in combo for maps to make them more realistic and make engine fell less like 2000s but due to this i cant, i have literally been trying everything, i asked chatgpt too  and showed it code and it was like 'it doesnt seem like something is wrong in this code please make sure you are correctly doing parallax mapping' so even chatgpt which has helped me in past cant help, so really hope you can check it out soon

**Comment by TheOverfloater** [comment]
I cannot guarantee I will be able to debug this very soon. I have about 3-4 other projects I help out with code, my own video game project on Pathos, and I have a full-time job at the same time I need to deal with. I will take a look when I have some free time.

**Comment by valina354** [comment]
> I cannot guarantee I will be able to debug this very soon. I have about 3-4 other projects I help out with code, my own video game project on Pathos, and I have a full-time job at the same time I need to deal with. I will take a look when I have some free time.

ok, im continuing to debug it myself and i noticed even when theres a dlight the drawfirst still runs and runs this but bindtexture no longer runs because i see theres code to prevent that when multipass so that could be issue, but im looking through code and i kinda dont understand what drawfinal is meant to do, is it to like overlay the dlight on the textures or something?
![image](https://github.com/user-attachments/assets/b540036a-9180-4931-9b7e-e9a19fe04746)
![image](https://github.com/user-attachments/assets/ab81282e-e680-4693-8af6-7e12e1a2c9c6)

**Comment by valina354** [comment]
i think its quite important i fix it since the parallax mapping looks so good it looks like this, in my opinion it turns the engine from looking like 2000s to bit more modern
![image](https://github.com/user-attachments/assets/eb92760c-6b13-46f6-ba66-48af3be34ae6)

**Comment by valina354** [comment]
i also fell like theres a tiny tiny bit of chance that maybe its caused by parallaxscale and parallaxlayers param not binding when in drawfinal, because i notice the surface darkens when parallax and dlight on which signals parallax is on? im not really sure how i would check that because vs 2022 debugger says 'unable to read memory'

**Comment by valina354** [comment]
i have literally tried everything now and still nothing, my only hope is if you figure out the issue when checking out the code

**Comment by valina354** [comment]
not related but i just noticed the new major pathos update released, i dont know how i will merge it into my branch tbh bcz its so massive and since i store my matrix engine on a company i dont have the merge button anymore, i guess i will have to merge it manually by going through each code

**Comment by valina354** [comment]
actually because of fact the new pathos update is so massive and i made mistake of not forking correctly i will have to restart development of matrix engine so till i get the parallax mapping back in i think you wont be able to check whats wrong

**Comment by valina354** [comment]
because of fact new pathos update was so massive now after merging everything the parallax no longer works it just makes texture look like this even tho the code is same from before, making it fully useless with or without dlight, so you will probably have to investigate that issue too but i sucesfully finished restarting development of my engine and readding everything so its ready to check whenever you can for the broken parallax mapping
![image](https://github.com/user-attachments/assets/9c5d2c40-de56-4509-8c6e-898a6e028ba9)

**Comment by valina354** [comment]
ok i have tried everything myself but i cant even fix this new issue so i guess you will have to investigate this too when checking it out, but since the new pathos update released hopefully you can try checking it out in the future, and new url of engine based on this is https://github.com/Soft-Sprint-Studios/Matrix_Engine and all changes related to parallax is at r_bsp.cpp and bsprenderer.bss

**Comment by valina354** [comment]
way parallax works is by making it so everything referencing ps_texcoord references ps_parallaxcoord when $branch parallax == 1, so when dlights are on it doesnt do it for some reason, i also cant really try anything anymore cuz parallax is broken anyways now so i guess i have to wait

**Comment by valina354** [comment]
i tested it and making ps_parallaxcord be normal ps_texcoord fixes it so its defintly issue with how parallax is calculated, but it worked before major pathos update, i wonder if new pathos update changed how ps_texcoord is handled?

**Comment by valina354** [comment]
i have no idea how but i was making a new testing map for auto exposure im adding to engine and put texture with parallax and it somehow works back again but doesnt still work in testparallax map i made, maybe its somehow an issue with the map like map got corrupted and for some reason placed a dlight i dont know, so luckily thats fixed (hopefully) its just issue with dlight now, so when ever you can try to look into that @TheOverfloater 
![image](https://github.com/user-attachments/assets/fb29e942-02c7-42e5-ab45-f6b4273c077d)

**Comment by valina354** [comment]
oh the parallax also doesnt seem to work for water, surfaces below water with parallax arent showing it (but at least this is less big issue and more liveable then with dlight)
![image](https://github.com/user-attachments/assets/6ac17786-234f-446b-8818-e26327b95bcd)

**Comment by valina354** [comment]
i also had idea which is that since parallax makes it so it turns ps_texcoord into ps_parallaxcoord, thats most likely reason why it doenst work with dlights, but i tested it and im able to send uniforms and they also work with dlights, so i had idea what if i removee the parallax determinator (will also save a determinator making it take less long to compile), make it always use parallax, but if theres no alpha texture in normal map (this will also save 1 texture uniform) just send default ps_texcoord at the parallax mapping function itself and this might fix issue without changing anything else and also require less C++ code, im not sure if this will work? i might try it myself

**Comment by valina354** [comment]
ok, i finished trying to do that but its not working it just makes it look like this, i really dont get whats wrong like why is everything turning whiteish
![image](https://github.com/user-attachments/assets/b16c3ae1-8de5-4e40-89c1-d7649c15948f)

**Comment by valina354** [comment]
i added this check too to ensure that things that dont have heightmap dont run but its still doing it even for those i dont understand really without dlight it is fine btw
![image](https://github.com/user-attachments/assets/6724e9ab-1ca7-4b31-8ca8-fafc50451afb)

**Comment by valina354** [comment]
well in total it seems to be worse when trying this way so i will revert back and wait till you can check what might be issue i guess

**Comment by TheOverfloater** [comment]
I can't promise when I will get to take a look at this issue, but until then I would recommend studying the engine code closer to try and understand how to apply parallax mapping in a way that doesn't break everything. Also note that I myself have very little to no idea of how parallax mapping is done, so I'd need to research it myself before I can say anything.

**Comment by valina354** [comment]
> I can't promise when I will get to take a look at this issue, but until then I would recommend studying the engine code closer to try and understand how to apply parallax mapping in a way that doesn't break everything. Also note that I myself have very little to no idea of how parallax mapping is done, so I'd need to research it myself before I can say anything.

parallax mapping uses ps_normal,ps_binormal and ps_tanget, normalize them as T,B,N, then transpose them with a function, then do a - ps_vertexpos, this is used for the direction vector, and then parallax mapping works by using raytracing based on number of steps with a heightmap that is * by a heightscale param and then alters the texture cordinates, so unless somehow ps_normal,ps_binormal,ps_tanget becomes unavailable when dlight is on, there should be no issue but there is which is why its very strange, basiclly whats being done here
![image](https://github.com/user-attachments/assets/67c44d9a-3b5f-4851-bcee-9a3ef6124e50)

**Comment by valina354** [comment]
this is best page i found for learning about parallax mapping (well parallax occlusion mapping is variant i use as its best) https://learnopengl.com/Advanced-Lighting/Parallax-Mapping

**Comment by valina354** [comment]
ok so more good news @TheOverfloater  i forgot to add parallax here at shader type 4 and after adding it it seems to have fixed it more! the changes also seem to be making parallax show in water now!
![image](https://github.com/user-attachments/assets/d39ebde5-f725-467f-b0d6-3ed1d6b47a35)
it looks like this now
![image](https://github.com/user-attachments/assets/34929fb3-72ba-49b6-bf93-fd898d21e39e)

however it doesnt really seem like theres a texture applied, and parallax is applying to other surfaces that dont specify parallax, if i add parallax here it fixes issue of applying to other surfaces but parallax disappears when dlight is on if the code is there, so its really strange, but this is first time parallax is actually seen applying with a dlight and closest to working i guess
![image](https://github.com/user-attachments/assets/fcbefe49-58d9-4b89-8453-29eb569ecc54)

**Comment by valina354** [comment]
> ok so more good news @TheOverfloater i forgot to add parallax here at shader type 4 and after adding it it seems to have fixed it more! the changes also seem to be making parallax show in water now! ![image](https://private-user-images.githubusercontent.com/80889633/353873195-d39ebde5-f725-467f-b0d6-3ed1d6b47a35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzgzNjYsIm5iZiI6MTcyMjQzODA2NiwicGF0aCI6Ii84MDg4OTYzMy8zNTM4NzMxOTUtZDM5ZWJkZTUtZjcyNS00NjdmLWIwZDYtM2VkMWQ2YjQ3YTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMDFjYmJiMDNmMGM0OWNkOTdkNDhiNTk4ZmM5NGZkNGI0NmFmNThkOGNkYzcxMjE0NTA0OTI5YzJjNWQ3ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNDKmmtRtJshKjfTBvGZq303AwwRZpPn-TK3iDc2iq8) it looks like this now ![image](https://private-user-images.githubusercontent.com/80889633/353873492-34929fb3-72ba-49b6-bf93-fd898d21e39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzgzNjYsIm5iZiI6MTcyMjQzODA2NiwicGF0aCI6Ii84MDg4OTYzMy8zNTM4NzM0OTItMzQ5MjlmYjMtNzJiYS00OWI2LWJmOTMtZmQ4OThkMjFlMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OWRmZDBkZjYwZjZhYjdlNmFmYjMyZTIwNTRjYWQxMTdjZWIyOTdhZmJmMmQ4ZTJmZDUxZGJjZmU4Yzk0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0DNliVKy8kQ--4qShvodaAKR6QJAS2zLxrgbS9FEny0)
> 
> however it doesnt really seem like theres a texture applied, and parallax is applying to other surfaces that dont specify parallax, if i add parallax here it fixes issue of applying to other surfaces but parallax disappears when dlight is on if the code is there, so its really strange, but this is first time parallax is actually seen applying with a dlight and closest to working i guess ![image](https://private-user-images.githubusercontent.com/80889633/353873755-fcbefe49-58d9-4b89-8453-29eb569ecc54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzgzNjYsIm5iZiI6MTcyMjQzODA2NiwicGF0aCI6Ii84MDg4OTYzMy8zNTM4NzM3NTUtZmNiZWZlNDktNThkOS00Yjg5LTg0NTMtMjllYjU2OWVjYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE1MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMGYyNTcwZTQxNDdjOWFiZGU3MTY0Y2UwN2ZmZjljZWY3MmVlZTVhYWU5NjAyODhiYWVlNTljOGJmZGQzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KdWYPGizc8_lnWrD56HO6WHKbPubGdMSzPUjsmjDLI8)

well on some maps it seems its this way on some not, its so confusing tbh

**Comment by valina354** [comment]
i think its really important i fix it the issue with dlight because it looks so awesome, like it looks 3d with low performance loss, and will probably help too to make scenes look better considering fact i cant use models, because my only option rn seems to be not using dlights anywhere and using parallax mapping, using parallax mapping only in certain areas and dlights only for important areas, or no parallax mapping anywhere, all of which arent that great, because outside i use dlight for csm light
![image](https://github.com/user-attachments/assets/24ea1363-aeb5-4cba-8b54-627dd7a87e5c)

**Comment by valina354** [comment]
> I can't promise when I will get to take a look at this issue, but until then I would recommend studying the engine code closer to try and understand how to apply parallax mapping in a way that doesn't break everything. Also note that I myself have very little to no idea of how parallax mapping is done, so I'd need to research it myself before I can say anything.

i will make sure all the parallax mapping code i added is is update to date  i guess to latest so when you take a look its up to date and i will make a parallax test map and texture so when you take a look its easier to debug

**Comment by valina354** [comment]
ok, i pushed to matrix engine the parallax testing map and example texture (its named autoexposuretest cuz i originaly was trying to add autoexposure to engine but its mostly parallax testing now), and you can test dlight with flashlight, so whenever you can check out the issue its easier

**Comment by valina354** [comment]
im doing more tests with parallax mapping and it looks very cool, it would take thousands of polygons to do same thing which is why i really need to fix the issue with dlight, i also notice with partially working dlight theres crazy performance loss which is strange vs no dlight, as if parallax is being done multiple times, and this is with more realistic lower samples and less depth
![image](https://github.com/user-attachments/assets/9afad671-4c8f-43a5-b4ed-ba598e023cb8)
![image](https://github.com/user-attachments/assets/23f5e502-d325-4e17-936a-ca888c65d8a8)


it just looks so cool in my opinion

**Comment by valina354** [comment]
![image](https://github.com/user-attachments/assets/db88bc31-3231-4038-8650-3ac5ec59ec35)

**Comment by TheOverfloater** [comment]
I am closing these Issues since they are not actually issues. In the future please raise such issues over in your fork of the engine and tag me at most, as the Pathos Issues page is getting extremely cluttered with non-issue Issues.
