### ISSUE TITLE
[Not an issue] Suggestion: Cubemaps on VBM models

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#39]
unless im wrong engine doesnt support cubemaps on VBM models by looking at the shader code, This makes anything outside of specular highlights on models not possible, this feature would allow models to use cubemaps for enviornment mapping

**Comment by TheOverfloater** [comment]
I did not implement cubemaps on VBM models yet because I was concerned about further shader bloat. I will look into this when I manage to optimize shader counts a bit in the VBM shader file.

**Comment by valina354** [comment]
> I did not implement cubemaps on VBM models yet because I was concerned about further shader bloat. I will look into this when I manage to optimize shader counts a bit in the VBM shader file.

i guess that makes sense, but since the engine might have parallax corrected cubemaps in future i think it would only work on brushes due to how parallax cubemaps work usually so if cubemaps are implemented on VBM models i think they would have to use non parallax cubemaps
