### ISSUE TITLE
Why does SV_linkmaptexturesandmaterials give failed to find material file for world texture even if its there?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#40]
i got this
![image](https://github.com/user-attachments/assets/24e9b292-60e9-44ac-861e-36d3abb5590f)
but it still gives
![image](https://github.com/user-attachments/assets/e2d542ca-e819-4db9-85a2-d24e1b9a5df5)
contents of pmf is
![image](https://github.com/user-attachments/assets/4821ccbb-4751-45fd-a4ef-ec28f6faddac)
am i doing something wrong?

**Comment by valina354** [comment]
hmm, i decided to add debugging code and it seems it doesnt search in the bricks directory?
![image](https://github.com/user-attachments/assets/14a4b831-2ab5-4eb3-a37b-13cf6fe34bca)

**Comment by valina354** [comment]
ooh wait its searching based on wad name i think

**Comment by valina354** [comment]
i was able to get it working but it resulted in this unorganized mess 💀 
![image](https://github.com/user-attachments/assets/3f3a7a9f-ceef-414c-bd16-ceb732af2ae5)

**Comment by TheOverfloater** [comment]
Unfortunately without a custom level editor, it is not possible to cut ties with .WAD files, and this is the reason why you need to place your textures under "textures/world/*wadname*" for the texture lookup to work. Because of this a better level of organization is just not possible right now.

**Comment by valina354** [comment]
> Unfortunately without a custom level editor, it is not possible to cut ties with .WAD files, and this is the reason why you need to place your textures under "textures/world/_wadname_" for the texture lookup to work. Because of this a better level of organization is just not possible right now.

i am making my own level editor based on hammertime so i think that would be possible at least on my branch its just that i dont know how i would make the compilers still calculate radiosity as they currenlty rely on WAD for lightmapres, and radiosity calc and probably more from what i know

**Comment by TheOverfloater** [comment]
It would need an enormous, massive rewrite of the VHLT tools to support both WAD and DDS/TGA textures, and to support storing paths to the individual textures.
