### ISSUE TITLE
[Not an issue] Is there a way to send params to particles in C++?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#41]
im recreating the entity env_dustpuff from source (https://developer.valvesoftware.com/wiki/Env_dustpuff), now in source it has scale,speed and dust color params which i want to add too, for pretty much all these its possible to do in the particle txt, however i need to add it to entity in C++ and send the new params, so is there way or would i need to overhaul particle system?

**Comment by TheOverfloater** [comment]
It is currently not supported to adjust anything in C++ apart from the origin and direction of particle systems. It could be added with a later update though, to make this customizable, but my biggest concern is not to end up with parameter bloat.

**Comment by valina354** [comment]
> It is currently not supported to adjust anything in C++ apart from the origin and direction of particle systems. It could be added with a later update though, to make this customizable, but my biggest concern is not to end up with parameter bloat.

ok, idea i have for this effect is to have a function say setparticleuniform or somthing like that to sets it, heres pseudocode of what i mean:
particle->setparticleuniform("max_particles", 50);

im not sure if something like that would be possible in future
