### ISSUE TITLE
whats -bumpmaps compile param?

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#42]
i noticed after compiling maps it doesnt seem like theres normal mapping unless theres a dynamic light (correct me if im wrong), when checking compiling maps .bat i noticed theres -bumpmaps and in compilers too, i set them to on but it doesnt seem like they do anything, + i thought normal mapping needs a normal map in .wad since you cant have normal mapping, without normal map, am i doing something wrong or is this something else?
![image](https://github.com/user-attachments/assets/ae6a1fd0-f83b-4370-985c-1497f077ada2)

**Comment by valina354** [comment]
this is with it on the -bumpmaps, i just cant tell if theres normal mapping going on from the normal light_spot, and if there is how is it working?
![image](https://github.com/user-attachments/assets/c7435ea6-2d81-4132-8fa0-6f1bfcebc51b)

**Comment by TheOverfloater** [comment]
I am pretty sure I can see bump mapping on the floor below. What -bumpmaps does, is that it tells RAD to compile lighting info into the BSP that tells the renderer where lighting comes from, and how it is distributed between ambient and direct lighting. You will need proper normal maps and specular maps to really make it look good though. You can compare by toggling the r_bumpmaps cvar.
You should never store your normalmap in the WAD either, that's solely a legacy feature and WAD textures cannot store the data you need for normal maps, as they're indexed 256 color palette textures. Your normal maps should always be TGA or DXT5 DDS textures if you really need compression.

**Comment by valina354** [comment]
> I am pretty sure I can see bump mapping on the floor below. What -bumpmaps does, is that it tells RAD to compile lighting info into the BSP that tells the renderer where lighting comes from, and how it is distributed between ambient and direct lighting. You will need proper normal maps and specular maps to really make it look good though. You can compare by toggling the r_bumpmaps cvar. You should never store your normalmap in the WAD either, that's solely a legacy feature and WAD textures cannot store the data you need for normal maps, as they're indexed 256 color palette textures. Your normal maps should always be TGA or DXT5 DDS textures if you really need compression.

im not storing them in wad, and i do have diffuse,normal,specular and ao (ao is part of my custom engine based on this that multiplies by a pbr ao map), but i notice it now i guess
