### ISSUE TITLE
[Not an issue] Suggestion: make rad compile model shadows

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#44]
i noticed models dont compile shadows as in below them and stuff, i have actually for past hours been checking this and i got it pretty much working but im not sure how legal variant that works for me is cuz i would pullrequest this change but i used this https://github.com/seedee/SDHLT/commit/1a845198cca853118f3c7d6b502ce7853ba0fbdc
![image](https://github.com/user-attachments/assets/8f5abebf-6fee-4d0a-b6c4-eec56c94c113)

**Comment by valina354** [comment]
everything pretty much seems legal in the shadow code i took from that repo except fact it uses original studio.h from half-life sdk

**Comment by valina354** [comment]
i noticed pathos engine studio.h seems to be compatible with the model shadows only issue is that Vector isnt found when adding the pathos studio.h for the model shadows so i cant compile

**Comment by valina354** [comment]
only issue i noticed with way im doing it is for some reason everything except fast mode makes model turn black but the lightmap itself with shadow is correct so that means the issue with model turning black is hopefully fixable
![image](https://github.com/user-attachments/assets/fbb5a549-5648-4142-8e62-368f2718fbd6)

**Comment by valina354** [comment]
example of no shadow vs shadow vs shadow with transparency vs high res textures which make shadow quality better
![image](https://github.com/user-attachments/assets/7e16d61c-4023-4324-bb9c-5ad9d341614d)
![image](https://github.com/user-attachments/assets/6db4335e-5f08-4a8a-bfe0-956189d0fed8)
![image](https://github.com/user-attachments/assets/46eefa3d-addf-4903-9826-9373e7035296)
![image](https://github.com/user-attachments/assets/877e78bf-8e14-4304-9b3d-40e9af442f12)

**Comment by valina354** [comment]
after dumping the bsp lightmaps its also visible there so that means i pretty much have it working except the fact model turns black for some reason
![image](https://github.com/user-attachments/assets/2f47f964-ed85-442a-abf7-81ad0e2fd0c1)

**Comment by TheOverfloater** [comment]
The reason the model turns black, is that models take lightvalues from the surface beneath their origin. It's the main reason why I haven't implemented such a feature yet, as it'd need some kind of baked model lighting. I don't have any idea how to add such a feature, nor the energy for it now. I would recommend you try using env_elight to try and counter-balance the black lighting on the model.

**Comment by valina354** [comment]
> The reason the model turns black, is that models take lightvalues from the surface beneath their origin. It's the main reason why I haven't implemented such a feature yet, as it'd need some kind of baked model lighting. I don't have any idea how to add such a feature, nor the energy for it now. I would recommend you try using env_elight to try and counter-balance the black lighting on the model.

oh, that sounds like bigger issue then i thought, i thought it was issue related to how i calc model shadows but that sounds even worse (btw im kinda surprised because the model shadows from sdhlt worked first try with basiclly no changes, that really shows how back ward compatible engine is without using leaked code), from what issue you are saying fix would be implementing lightmapped models similar to source (https://developer.valvesoftware.com/wiki/$lightmap) but that would be very complex, kinda sad since i will make my games on pathos and might use lots of models but i guess theres work arounds to try to fake itlike you said with env_elight, but i think it might cause high performance loss if i have lots of models with an env_elight

**Comment by valina354** [comment]
> The reason the model turns black, is that models take lightvalues from the surface beneath their origin. It's the main reason why I haven't implemented such a feature yet, as it'd need some kind of baked model lighting. I don't have any idea how to add such a feature, nor the energy for it now. I would recommend you try using env_elight to try and counter-balance the black lighting on the model.

wait, what type of lighting is models using? i thought it used per vertex lighting but based on what you are saying its not that, because if it was vertex lighting there would be no problems, similar to source engine (https://developer.valvesoftware.com/wiki/Texture_shadows)

**Comment by valina354** [comment]
i also remember there was a project on xash3d (was it paranoia or something else) that had lightmapped models in compiler, so i wonder if that could intheory help to add lightmapped models, only thing is it would require making it compatible with vbm models

**Comment by valina354** [comment]
> i also remember there was a project on xash3d (was it paranoia or something else) that had lightmapped models in compiler, so i wonder if that could intheory help to add lightmapped models, only thing is it would require making it compatible with vbm models

oh, not paranoia but this https://github.com/SNMetamorph/PrimeXT/blob/master/utils/pxrad/model_lightmaps.cpp
or this
https://twhl.info/thread/view/20487

**Comment by valina354** [comment]
or this for model vertex lighting https://github.com/SNMetamorph/PrimeXT/blob/master/utils/pxrad/vertexlight.cpp

so theres defintly lots of resources to attempt to do something like that

**Comment by valina354** [comment]
i might actually be able to try to add model vertex lighting or lightmapping, its just i kinda cant untill studiomdl rewrite is done as it requires adding new things to vbm model/mdl

**Comment by valina354** [comment]
i asked google ai how the vertex lighting is applied to the model from the vertexlight.cpp cuz i dont have time to manually look through it and most of it seems to be done in rad just it has to be applied to model in engine, so if these are added to vbm format i think there wont be issue with model shadows and the model lighting will look better
![image](https://github.com/user-attachments/assets/011e171c-a423-4eb1-974f-f0f7bbe0ee7b)

**Comment by valina354** [comment]
my main issue is i have previously worked with source engine (before moving to pathos so i can make my own standalone games without copyright issue) so i like models since while yes its possible to turn models into brushes (hammertime supporst turning obj into brushes so its exactly same as models but more custom like texture flipping and stuff7 and it also causes 2 triangles instead of one that could be just a brush) my issue is i fell like it would cause performance loss more then models, unless im wrong, do you know if brushes are more intensive then models? in terms of fps, and im also worried brushes would cause too much map size, like even 1000 vertecies model which is low would require around 2000 brushes considering its 2 triangles and i think it would cause way too much storage and very complex to apply textures @TheOverfloater

**Comment by valina354** [comment]
like if necesary i might go that route of using brushes that are turned from models but use as little verticies as possible like only 64  triangles(128 brushes) as its not like all models need lots of polygons, like for example most props i would use like desks,drawers,cameras or stuff dont really need more then like 128 brushes maybe some dont even need more then 32

**Comment by valina354** [comment]
i think it would work along with making them func_detail for more performance (wait does func_detail or equivelant exist in pathos? @TheOverfloater)

**Comment by TheOverfloater** [comment]
You could try using the "Light Origin" to set another point to sample lightvalues from in the level to get around this. Brushes will always be more resource-intensive than models, because they are more expensive to render. I would really just note that I am not really open to doing such enormous modifications on the engine like implementing model lightmapping. It's a ton of work, more than I am willing to take up with my limited free time.

**Comment by valina354** [comment]
> You could try using the "Light Origin" to set another point to sample lightvalues from in the level to get around this. Brushes will always be more resource-intensive than models, because they are more expensive to render. I would really just note that I am not really open to doing such enormous modifications on the engine like implementing model lightmapping. It's a ton of work, more than I am willing to take up with my limited free time.

ok, personally i have lot of free time but lack expertise to do it sadly

**Comment by valina354** [comment]
> You could try using the "Light Origin" to set another point to sample lightvalues from in the level to get around this. Brushes will always be more resource-intensive than models, because they are more expensive to render. I would really just note that I am not really open to doing such enormous modifications on the engine like implementing model lightmapping. It's a ton of work, more than I am willing to take up with my limited free time.

theres also easier method of vertex lighting instead, which is what most games used for models in early 2000s, instead of light maps it calculates light color and brightness at each vertex of model and then linearly interpolated across the model this is easier then a lightmap because all you have to do is calculate lighting for that vertex at that point, then for others, then apply them to model, this means models with more vertices look better but is usually easier to do then lightmapping and would be simpler and less time consuming, at least i think

also since you mentioned light origin i think it would work but issue is i would need to have exact same lighting and exact same light origin, which i think would be possible if i make a duplicate of map and put it beside it, but it wouldnt be worth it for just light origin really, so i might just go brush approach tbh, i think its better either way because not only do brushes have lightmaps, but also bounced lighting and only use models for things like outside trees where i use dlight to fake csm, weapons,npcs and thats about it, brushes are models either way, my only concern is that i need to somehow keep brush count low while looking good enough, so like somehow keep a say 1000 vertices model into like 32 brushes

**Comment by valina354** [comment]
i just now realized, what do i do about textures for model brushes? since lets say i turn this model (https://polyhaven.com/a/utility_box_02), use blender to lower its polygons as its not too complex model, then i have the model itself as brushes using hammer time to turn obj to brushes but what do i do about textures? because models use maps looking like this to apply to entire surface, do you have any idea on how i would go about this or no? @TheOverfloater 
![image](https://github.com/user-attachments/assets/45da9739-2550-40ca-89a5-02dab8b01734)

**Comment by TheOverfloater** [comment]
Replacing VBM models with brushmodels for props is a terrible idea. Brushmodels cannot reproduce the same level of small details and lighting that VBM models have, and you will also have severe performance issues.

**Comment by valina354** [comment]
> Replacing VBM models with brushmodels for props is a terrible idea. Brushmodels cannot reproduce the same level of small details and lighting that VBM models have, and you will also have severe performance issues.

yeah i get that but im not sure what to do else then because like models have big issues which is that they dont do shadows, dont have lightmaps and dont bounce around light (i think) so my scenes would look kinda bad i think and only solution for that seems to be to implement model lightmaps and somehow make models bounce around lights but thats well too complex for me to do and i have also been searching for programmers who want to do it but i cant find anyone since everyone wants money which i dont have so rn brush models seem like only sollution

**Comment by TheOverfloater** [comment]
I'll be honest, I sincerely do not think Pathos is a good fit for what you want to achieve with your engine. This sounds like something more suited to a more advanced engine than Pathos. Pathos is supposed to be a GoldSrc-like engine with some Source-like features, but at it's core it's meant to have a GoldSrc-like workflow with CSG geometry. Brush geometry is a poor solution for highly detailed scenes and models because you lose any details below the 1.0 unit size, you have very little control over smoothing groups especially with dynamic lighting, and you will have severe performance issues if you use too many brushes in a level to use instead of VBM models. It was never even an idea to have parallax mapping, or to add radiosity to studiomodels, or have models cast shadows, because it was never in scope for an engine that was always just meant to be an opensource GoldSrc replacement with a few extras.

Second, I saw your posts on other sites, and it's not surprising you didn't awake any real interest. Coming from experience as someone who has done video game development for over 15 years now, you will not get volunteers onboard without having something substantial to show in terms of progress. I'm not saying test levels, I am talking about actual gameplay, actual campaign content, actual final levels, actual animated models. You cannot achieve this without having the programming, level design and modelling knowledge to produce this content. Without learning more about C/C++ and OpenGL programming you will always depend on someone else to fix issues for you, and other people have very limited time which they already need to mostly spend on just getting by day-by-day. I learned this myself as I was modding or HL1, and I ended up going through the process of sitting down and learning programming. Then I learned how to make models, how to animate. TL;DR people won't join a project that has nothing to show apart from a few tests with textures, they'll want to see substantial progress before committing to it.

I think what would be more fitting for your needs is something like the Doom 3 engine, which has a more advanced level format more suited to your needs. However even with that you cannot do much without knowing how to rework the engine into what you need out of it. The matter of the fact is, if you want to get into game development, you need to either expand your knowledge and skillset, or make compromises with what you want to achieve.

**Comment by valina354** [comment]
> I'll be honest, I sincerely do not think Pathos is a good fit for what you want to achieve with your engine. This sounds like something more suited to a more advanced engine than Pathos. Pathos is supposed to be a GoldSrc-like engine with some Source-like features, but at it's core it's meant to have a GoldSrc-like workflow with CSG geometry. Brush geometry is a poor solution for highly detailed scenes and models because you lose any details below the 1.0 unit size, you have very little control over smoothing groups especially with dynamic lighting, and you will have severe performance issues if you use too many brushes in a level to use instead of VBM models. It was never even an idea to have parallax mapping, or to add radiosity to studiomodels, or have models cast shadows, because it was never in scope for an engine that was always just meant to be an opensource GoldSrc replacement with a few extras.
> 
> Second, I saw your posts on other sites, and it's not surprising you didn't awake any real interest. Coming from experience as someone who has done video game development for over 15 years now, you will not get volunteers onboard without having something substantial to show in terms of progress. I'm not saying test levels, I am talking about actual gameplay, actual campaign content, actual final levels, actual animated models. You cannot achieve this without having the programming, level design and modelling knowledge to produce this content. Without learning more about C/C++ and OpenGL programming you will always depend on someone else to fix issues for you, and other people have very limited time which they already need to mostly spend on just getting by day-by-day. I learned this myself as I was modding or HL1, and I ended up going through the process of sitting down and learning programming. Then I learned how to make models, how to animate. TL;DR people won't join a project that has nothing to show apart from a few tests with textures, they'll want to see substantial progress before committing to it.
> 
> I think what would be more fitting for your needs is something like the Doom 3 engine, which has a more advanced level format more suited to your needs. However even with that you cannot do much without knowing how to rework the engine into what you need out of it. The matter of the fact is, if you want to get into game development, you need to either expand your knowledge and skillset, or make compromises with what you want to achieve.

i have been planning to slowly expand the engine while making my own game, like i was planning to soon try to add controlable lightmap scale in editor similar to source engine which i might try soon and from start months ago i was planning to add parallax mapping (which is now added except the dlight bug that is like game engine gods want to force me to not use parallax mapping) and more things like screen space ambient occlusion and screen space reflections but that got ruined by the fact i cant output the screen space specular,normals,position and albedo to postprocess shader, my main reason that i want to use pathos is that since i have worked with source engine a lot im kinda stuck to csg game engines and prebuilt entities, like without prebuilt entities i cant do anything or be able to build even simple rooms without csg, like i have tried many engines since november 2023 and literally wasting 9 months already which are  unity,unreal,idtech,trying to make my own custom engine,goldsrc before realizing that goldsrc has license that it cant be used commerically too, crytech, even tried reaching out to valve for a source engine license but nothing ever came back and i couldnt anyways cuz valve needs nda which i cant sign as im teenager, ultra engine (which i spent 60 euros on for no reason), copper cube, and finally pathos after someone in valve modding community recommanded it to me because i had started a Xash3d unleakified project that was aiming to rewrite the half-life sdk for xash3d and was looking for people and no one joined and then i got recommanded pathos as alternative, im pretty much planning to begin making game inspired by half-life 2 but way different and more original, and since im also teenager i dont have money to like pay a professional graphics devs lots of euros to implement me all the important graphical features over months and basiclly turn engine into modern engine in like a year while keeping the entities and csg work flow or at least it will be like this for few more years when i will have job and be able to pay any graphics programmers so rn my only choice seems to be pathos but im planning to start making my own game rn to try to be revolutinary cuz i have like 1 month left of summer school vacation but im in preparing asset part and about to finish with brush textures

btw i decided to try to see how big performance loss brushes do and this is normal amount of brushes, fps limited to 1000 fps to prevent bugs
![image](https://github.com/user-attachments/assets/0ea8eeff-24fd-4df1-b187-3908e02e1cdf)

and this is with hundreds of brushes, fps drop by 200 (edit: in screenshot its 400 less but in game it seems to keep hovering) or well probably more but fps counter doesnt seem to go past 1000 which is well lot but well there is this many solids and in game play not every brush would be rendererd at once, altho idk if my way of testing is more flawed because they are in same area, altho there is water in here so it renders twice lowering fps so this test is more flawed cuz in most areas i wouldnt have water
![image](https://github.com/user-attachments/assets/55d42b6f-d93d-4775-8cf3-cace959474b6)
![image](https://github.com/user-attachments/assets/7a82d0ea-e82a-47b1-ae36-9323ae541ff5)

btw as for doom 3 you mentioned i did actually try it too months ago, i was close to using it but gave up because doom 3 does not have lightmaps which ruins bounced lighting and that was too big issue so this is why pathos is like my only choice rn really

and for trying to find graphics programmers i even gave benefits like getting any free games my company makes like future ones and getting special discord role and stuff but that didnt seem to incentivize people

**Comment by TheOverfloater** [comment]
I started working on custom renderers in GoldSrc when I was just 18. Truth is video game development is about patience, and not about jumping right at the heavy-handed features. I would really recommend you start simple, and just create content you know to create while experimenting with more advanced features. Work your way up as your skills improve.
Also it's hard to incentivize people with things that don't exist yet. Trying to make your own game company in the future is a rather bold endeavor that is far more difficult than you realize, and you need people for it. If I were you I'd work with what Pathos has to offer now, try to produce some content that you can show off to people so they become interested in your project. One of your problems is you're already jumping at advanced features you don't know how to make work. Now I can help fix feature A for you, but then you'll have feature B you need, then feature C. I just don't have the time or the willingness to commit to being a full-time developer on your game.

Thing is, you need to first learn the skills needed to code, map, and model a game before you'll have anyone coming on to work on it. I did the same, I was in a situation similar to yours. I had to learn these skills too. So take my advice with some weight to it at least. Start simple, learn, and learn a lot, and then do more complex things. You need to be patient with these goals.

**Comment by valina354** [comment]
> I started working on custom renderers in GoldSrc when I was just 18. Truth is video game development is about patience, and not about jumping right at the heavy-handed features. I would really recommend you start simple, and just create content you know to create while experimenting with more advanced features. Work your way up as your skills improve. Also it's hard to incentivize people with things that don't exist yet. Trying to make your own game company in the future is a rather bold endeavor that is far more difficult than you realize, and you need people for it. If I were you I'd work with what Pathos has to offer now, try to produce some content that you can show off to people so they become interested in your project. One of your problems is you're already jumping at advanced features you don't know how to make work. Now I can help fix feature A for you, but then you'll have feature B you need, then feature C. I just don't have the time or the willingness to commit to being a full-time developer on your game.
> 
> Thing is, you need to first learn the skills needed to code, map, and model a game before you'll have anyone coming on to work on it. I did the same, I was in a situation similar to yours. I had to learn these skills too. So take my advice with some weight to it at least. Start simple, learn, and learn a lot, and then do more complex things. You need to be patient with these goals.

ok, btw i really hope you will be able to help me at least fix the issue with parallax mapping disappearing with dlight because it will partially fix my issue, because parallax mapping makes things look 3d it can be used in clever ways to make almost like 3d geometry, heres example from learn opengl image on left one how it can be used to make it look 3d and not require an actual 3d model and at least if surfaces have 3d like effect it will lower needing to use models to detail i think at least a bit less models required
![image](https://github.com/user-attachments/assets/997acc67-87df-453d-a42f-42ce00d75469)

**Comment by TheOverfloater** [comment]
I will take a look as soon as I can to try and help fix it.

**Comment by valina354** [comment]
btw i just now realized, it seems dlights have a static option which does not build any further shadows then first pass, which unless im wrong does it mean theres no fps loss past first pass? so there could be low fps on first frame then normal fps, allowing it to be used as normal lights? because if so then its seems to be working as alternative, the only issue is  that theres no bounced light, which im not sure if theres any way to like modify the compiler to build bounced lighting for dlight if a flag is set for like the brushes, allowing it to be used as a normal light source but looks better and  affects models correctly @TheOverfloater  (btw sorry for pinging so much, i think there should be a discussions page instead of talking here as it doesnt make sense really, something like this https://docs.github.com/en/discussions/quickstart)
![image](https://github.com/user-attachments/assets/d0ee13d3-8392-437d-b69e-f36ea75cd94d)

**Comment by valina354** [comment]
i just realized that while this seems to work, if i write code to add bounce light to dlight for when its static, then it will cause issue where the  model will suddenly be brighter from the lightmap and also no more model shadow i guess or less powerfull, every sollution is seeming to be to somehow implement model lightmap which unless i find someone who can do that i probably cant

**Comment by valina354** [comment]
> The reason the model turns black, is that models take lightvalues from the surface beneath their origin. It's the main reason why I haven't implemented such a feature yet, as it'd need some kind of baked model lighting. I don't have any idea how to add such a feature, nor the energy for it now. I would recommend you try using env_elight to try and counter-balance the black lighting on the model.

wait a sec, isnt model lightmapping just about calculating lighting on the model with a lightmap similar to brush and then overlaying it on model? it doesnt sound that hard, i wonder if in order to replicate this what if i calculate model lightmapping in a software like blender by replicating the map in blender with only lights and brushes and models, make it so models can support a $lightmap param where you can input the lightmap texture, and then if the model has shadows, multiply the model by the lightmap texture calculated in blender and then exported to game to do lightmapping this would mean you would have to use a different model for every different scene even if its the same but it could still work, do you think that would work or no? its one of work arounds i just thought of, i think it would work considering my engine based on this has parallax occlusion mapping once dlight is fixed so i can use that to make scenes seem like they have more models then they do so i use models or props less and stuff @TheOverfloater

**Comment by valina354** [comment]
> > The reason the model turns black, is that models take lightvalues from the surface beneath their origin. It's the main reason why I haven't implemented such a feature yet, as it'd need some kind of baked model lighting. I don't have any idea how to add such a feature, nor the energy for it now. I would recommend you try using env_elight to try and counter-balance the black lighting on the model.
> 
> wait a sec, isnt model lightmapping just about calculating lighting on the model with a lightmap similar to brush and then overlaying it on model? it doesnt sound that hard, i wonder if in order to replicate this what if i calculate model lightmapping in a software like blender by replicating the map in blender with only lights and brushes and models, make it so models can support a $lightmap param where you can input the lightmap texture, and then if the model has shadows, multiply the model by the lightmap texture calculated in blender and then exported to game to do lightmapping this would mean you would have to use a different model for every different scene even if its the same but it could still work, do you think that would work or no? its one of work arounds i just thought of, i think it would work considering my engine based on this has parallax occlusion mapping once dlight is fixed so i can use that to make scenes seem like they have more models then they do so i use models or props less and stuff @TheOverfloater

wait a sec, to prevent using many different model names if i do what i said do you think it would be possible to like write system for detecting model position in the  texture pmf and then using one of the texture lightmaps if so? heres example in posedo code of what i mean, like how hard would it be to code it:
#if map == test_lightmapmodel && pos=437,34,50
$texture lightmap texture_lightmapmodel0
#end
#if map == test_lightmapmodel && pos=472,50,74
$texture lightmap texture_lightmapmodel1
#end

**Comment by TheOverfloater** [comment]
Calculating lightmaps for models is not as simple, because you can't just rely on Blender to do it for every unique model in a level, and then also separate that into a light vector map, ambient map and diffuse map. This again is adding a ton of more bloat to the render code for VBM models, but also models have overlap sometimes where multiple parts of the model use the same UV coords, which means that they cannot store light values properly.
If you want this feature, you're free to try and implement it into your engine version, but this isn't something I am going to invest my limited free time into. I don't see it as worth spending time implementing.

**Comment by valina354** [comment]
> Calculating lightmaps for models is not as simple, because you can't just rely on Blender to do it for every unique model in a level, and then also separate that into a light vector map, ambient map and diffuse map. This again is adding a ton of more bloat to the render code for VBM models, but also models have overlap sometimes where multiple parts of the model use the same UV coords, which means that they cannot store light values properly. If you want this feature, you're free to try and implement it into your engine version, but this isn't something I am going to invest my limited free time into. I don't see it as worth spending time implementing.

my main focus is to use model lightmap in way i said once i get it into my engine version is to use it on simpler models, so mainly simpler props, its not like im gonna use model lightmapping on models that are like an entire level or like models that are an entire building with like tens of thousands of polygons, which i think if models are less detailed  theres like lower chance of them using same UV coords?

**Comment by TheOverfloater** [comment]
Look, it's up to you. If you want to add this feature, go for it. Since I haven't even tried adding such a feature, I wouldn't even know where to begin, and I don't intend on adding this in the future either.

**Comment by valina354** [comment]
> Look, it's up to you. If you want to add this feature, go for it. Since I haven't even tried adding such a feature, I wouldn't even know where to begin, and I don't intend on adding this in the future either.

im looking at how bsp does lightmap so i can try to figure out at least if i can get lightmaps working through baking them in blender then getting them in game, im trying to figure out what the different names of lightmap mean so i can learn how they are done in  bsp so i can figure out how i can make the same ones in blender or like write a plugin or something to do same thing what does baselightmap,difflightmap and lightvecstex mean? is it this?:
baselightmap = ambient map
difflightmap = diffuse map
lightvecstex = light vector

is it correct?

so im guessing i would have to add multiple params to vbm model for each of them, so that when model shadows are on i can use it, turn all the lightmaps from blender into dds (btw do you know what lightmap res should be used for 1024x1024 textures since i dont really know) and then apply them similar to bsp and i think that should be it and i would have lightmapped models, it would of course make it complex to make for each model so i would probably do it at end of like my game dev or something or in testing maps but still would look way way better then current model lighting system i think

**Comment by TheOverfloater** [comment]
You need to figure this out on your own, because I never tried adding a feature like this. Also, I would recommend studying the code yourself and checking out what data is what, because if you look at the code it'll become obvious. I can't be here all the time to help you with every little thing.
