### ISSUE TITLE
Couldn't run Pathos on a specific machine

### ISSUE THREAD

**Issue by Aynekko** [TheOverfloater/pathos-public#48]
![image](https://github.com/user-attachments/assets/04b6de17-fd54-4361-8619-6e9751b69873)
I can't find the location of the log file, I will upload it once you tell me where it is.
Running x64 Pathos. Didn't even get to the menu.
The machine is:
Windows 7, i3-2100, GTX 650, video driver 341.81.

**Comment by TheOverfloater** [comment]
You should have some logs under "Pathos Engine/pathos/logs", can you please attach them to this issue?

**Comment by Aynekko** [comment]
I checked "C:\pathos-public-main\pathos", there are folders like dlls, fonts, maps, but no logs folder.
I run pathos_x64.exe without any specified parameters if that matters.

**Comment by TheOverfloater** [comment]
Can you please create the "logs" folder manually and try again?

**Comment by Aynekko** [comment]
Yep, that worked.
water_0_fs_debug.txt
```
0(7) : error C7532: global type sampler2DRect requires "#version 140" or later
0(7) : error C0000: ... or #extension GL_ARB_texture_rectangle : enable
```

**Comment by TheOverfloater** [comment]
Thank you. I just pushed a change to the water shader script, can you please check on your end?

**Comment by Aynekko** [comment]
It works.
